name: Deploy
on:
  push:
    branches:
      - master
  pull_request:
  workflow_call:
    inputs:
      website_repository:
        type: string
        default: tweag/nickel-lang.org
      website_ref:
        type: string
        default: master
      nickel_repository:
        type: string
      nickel_ref:
        type: string
      production_deploy:
        required: true
        type: boolean
    secrets:
      CACHIX_AUTH_TOKEN:
        required: false
      NETLIFY_AUTH_TOKEN:
        required: false
      NETLIFY_SITE_ID:
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          repository: ${{ inputs.website_repository }}
          ref: ${{ inputs.website_ref }}
      - name: Checkout Nickel
        if: ${{ inputs.nickel_repository && inputs.nickel_ref }}
        run: |
          cd nickel
          git remote set-url origin https://github.com/${{ inputs.nickel_repository }}
          git fetch origin ${{ inputs.nickel_ref }}
          git checkout ${{ inputs.nickel_ref }}
      - name: Installing Nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Setup Cachix
        uses: cachix/cachix-action@v10
        with:
          name: nickel
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build WASM
        run: |
          (cd nickel; git fetch --unshallow) # Flakes needs non-shallow
          nix build nickel/#buildWasm
          ln -s result/nickel-repl nickel-repl
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Build
        run: |
          npm ci --only=production
          npm run build
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          production-branch: 'master'
          production-deploy: ${{ inputs.production_deploy }}
          publish-dir: 'public'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: false
          enable-commit-status: true
          overwrites-pull-request-comment: false
